
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false

    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    tomcat:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-idle: 100
      max-wait: 30000
      time-between-eviction-runs-millis: 180000
      min-evictable-idle-time-millis: 180000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      connection-properties: oracle.net.CONNECT_TIMEOUT=180000;oracle.jdbc.ReadTimeout=180000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MysqlDialect
    show-sql: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制)
        max-idle: 8  #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接





wx:
  #小程序ID
  appId: wx0aa1d682756a4f2e
  #小程序密钥
  secret: 00e48588e8656e30b25dcf1e1e6a88c0
  #商户号
  mchId:
  #支付签名
  paySignKey:
  #交易类型
  tradeType: JSAPI
  #证书名称，对应不同的商户号
  certName: /cert/apiclient_cert.p12
  #支付回调地址
  notifyUrl: https://www.yourdomain.com/platform-framework/api/notify
  #获取code的请求地址
  codeUrl: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
  #获取Web_access_tokenhttps的请求地址
  webAccessTokenHttps: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  #拉取用户信息的请求地址
  userMessageUrl: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
  #微信统一下单接口路径
  uniformOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  #退款地址
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款查询地址
  refundQueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
  #微信查询订单状态
  orderQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery

ali:
  webAccessTokenHttps: https://openapi.alipay.com/gateway.do
  appId:
  privateKey:
  pubKey:

host:
  url: http://10.32.160.174:${server.port}
  port: ${server.port}