
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mymall?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    tomcat:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-idle: 100
      max-wait: 30000
      time-between-eviction-runs-millis: 180000
      min-evictable-idle-time-millis: 180000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      connection-properties: oracle.net.CONNECT_TIMEOUT=180000;oracle.jdbc.ReadTimeout=180000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MysqlDialect
    show-sql: true


